name: Publish
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v1
      - run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login --username ${{ secrets.DOCKER_USERNAME }} --password-stdin
      - run: docker build -t ${{ secrets.DOCKER_REPO }}/${{ secrets.DOCKER_IMAGE }}:latest -t ${{ secrets.DOCKER_REPO }}/${{ secrets.DOCKER_IMAGE }}:${GITHUB_SHA} .
      - run: docker push ${{ secrets.DOCKER_REPO }}/${{ secrets.DOCKER_IMAGE }}:latest
      - run: docker push ${{ secrets.DOCKER_REPO }}/${{ secrets.DOCKER_IMAGE }}:${GITHUB_SHA}